export const BIBLE_BOOKS = [
  { id: 'genesis', name: 'Gênesis', chapters: 50, testament: 'VT' },
  { id: 'exodus', name: 'Êxodo', chapters: 40, testament: 'VT' },
  { id: 'leviticus', name: 'Levítico', chapters: 27, testament: 'VT' },
  { id: 'numbers', name: 'Números', chapters: 36, testament: 'VT' },
  { id: 'deuteronomy', name: 'Deuteronômio', chapters: 34, testament: 'VT' },
  { id: 'joshua', name: 'Josué', chapters: 24, testament: 'VT' },
  { id: 'judges', name: 'Juízes', chapters: 21, testament: 'VT' },
  { id: 'ruth', name: 'Rute', chapters: 4, testament: 'VT' },
  { id: '1 samuel', name: '1 Samuel', chapters: 31, testament: 'VT' },
  { id: '2 samuel', name: '2 Samuel', chapters: 24, testament: 'VT' },
  { id: '1 kings', name: '1 Reis', chapters: 22, testament: 'VT' },
  { id: '2 kings', name: '2 Reis', chapters: 25, testament: 'VT' },
  { id: '1 chronicles', name: '1 Crônicas', chapters: 29, testament: 'VT' },
  { id: '2 chronicles', name: '2 Crônicas', chapters: 36, testament: 'VT' },
  { id: 'ezra', name: 'Esdras', chapters: 10, testament: 'VT' },
  { id: 'nehemiah', name: 'Neemias', chapters: 13, testament: 'VT' },
  { id: 'esther', name: 'Ester', chapters: 10, testament: 'VT' },
  { id: 'job', name: 'Jó', chapters: 42, testament: 'VT' },
  { id: 'psalms', name: 'Salmos', chapters: 150, testament: 'VT' },
  { id: 'proverbs', name: 'Provérbios', chapters: 31, testament: 'VT' },
  { id: 'ecclesiastes', name: 'Eclesiastes', chapters: 12, testament: 'VT' },
  { id: 'song of solomon', name: 'Cânticos', chapters: 8, testament: 'VT' },
  { id: 'isaiah', name: 'Isaías', chapters: 66, testament: 'VT' },
  { id: 'jeremiah', name: 'Jeremias', chapters: 52, testament: 'VT' },
  { id: 'lamentations', name: 'Lamentações', chapters: 5, testament: 'VT' },
  { id: 'ezekiel', name: 'Ezequiel', chapters: 48, testament: 'VT' },
  { id: 'daniel', name: 'Daniel', chapters: 12, testament: 'VT' },
  { id: 'hosea', name: 'Oséias', chapters: 14, testament: 'VT' },
  { id: 'joel', name: 'Joel', chapters: 3, testament: 'VT' },
  { id: 'amos', name: 'Amós', chapters: 9, testament: 'VT' },
  { id: 'obadiah', name: 'Obadias', chapters: 1, testament: 'VT' },
  { id: 'jonah', name: 'Jonas', chapters: 4, testament: 'VT' },
  { id: 'micah', name: 'Miquéias', chapters: 7, testament: 'VT' },
  { id: 'nahum', name: 'Naum', chapters: 3, testament: 'VT' },
  { id: 'habakkuk', name: 'Habacuque', chapters: 3, testament: 'VT' },
  { id: 'zephaniah', name: 'Sofonias', chapters: 3, testament: 'VT' },
  { id: 'haggai', name: 'Ageu', chapters: 2, testament: 'VT' },
  { id: 'zechariah', name: 'Zacarias', chapters: 14, testament: 'VT' },
  { id: 'malachi', name: 'Malaquias', chapters: 4, testament: 'VT' },
  { id: 'matthew', name: 'Mateus', chapters: 28, testament: 'NT' },
  { id: 'mark', name: 'Marcos', chapters: 16, testament: 'NT' },
  { id: 'luke', name: 'Lucas', chapters: 24, testament: 'NT' },
  { id: 'john', name: 'João', chapters: 21, testament: 'NT' },
  { id: 'acts', name: 'Atos', chapters: 28, testament: 'NT' },
  { id: 'romans', name: 'Romanos', chapters: 16, testament: 'NT' },
  { id: '1 corinthians', name: '1 Coríntios', chapters: 16, testament: 'NT' },
  { id: '2 corinthians', name: '2 Coríntios', chapters: 13, testament: 'NT' },
  { id: 'galatians', name: 'Gálatas', chapters: 6, testament: 'NT' },
  { id: 'ephesians', name: 'Efésios', chapters: 6, testament: 'NT' },
  { id: 'philippians', name: 'Filipenses', chapters: 4, testament: 'NT' },
  { id: 'colossians', name: 'Colossenses', chapters: 4, testament: 'NT' },
  { id: '1 thessalonians', name: '1 Tessalonicenses', chapters: 5, testament: 'NT' },
  { id: '2 thessalonians', name: '2 Tessalonicenses', chapters: 3, testament: 'NT' },
  { id: '1 timothy', name: '1 Timóteo', chapters: 6, testament: 'NT' },
  { id: '2 timothy', name: '2 Timóteo', chapters: 4, testament: 'NT' },
  { id: 'titus', name: 'Tito', chapters: 3, testament: 'NT' },
  { id: 'philemon', name: 'Filemom', chapters: 1, testament: 'NT' },
  { id: 'hebrews', name: 'Hebreus', chapters: 13, testament: 'NT' },
  { id: 'james', name: 'Tiago', chapters: 5, testament: 'NT' },
  { id: '1 peter', name: '1 Pedro', chapters: 5, testament: 'NT' },
  { id: '2 peter', name: '2 Pedro', chapters: 3, testament: 'NT' },
  { id: '1 john', name: '1 João', chapters: 5, testament: 'NT' },
  { id: '2 john', name: '2 João', chapters: 1, testament: 'NT' },
  { id: '3 john', name: '3 João', chapters: 1, testament: 'NT' },
  { id: 'jude', name: 'Judas', chapters: 1, testament: 'NT' },
  { id: 'revelation', name: 'Apocalipse', chapters: 22, testament: 'NT' }
];
